Web/Models/Announcement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Web.Models
{
    public class Announcement
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter a Title" )]
        [StringLength(244)]
        public String Title { get; set; }
        public DateTime DateTime { get; set; }
        public String Author { get; set; }
        [Required]
        public string Content { get; set; }
        //link announcement to user
        public virtual ApplicationUser User { get; set; }
    }
}

Web/Models/AnnouncementView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class AnnouncementView
    {
        public Announcement Announcement;
        public Comment Comment;
        public List<Comment> Comments;
    }
}

Web/Controllers/AnnouncementsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class AnnouncementsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        
        // GET: Announcements
        public ActionResult Index()
        {
            if (User.IsInRole(RoleName.Lecturer))
            {
                return View("Index");
            }else
            {
                return View("IndexStudent");
            }
            
        }

        // GET: Announcements/Details/5
        public ActionResult Details(ViewedPost viewedPost,int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Announcement announcement = db.Announcements.Find(id);
            if (announcement == null)
            {
                return HttpNotFound();
            }
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(
                x => x.Id == currentUserId);

            

            //if user is not a lecturer add it to the ViewwedPost db
            if (!User.IsInRole(RoleName.Lecturer))
            {
                var tmp = db.ViewedPosts.Any(x => x.AnnouncementId == id && x.User.Id == currentUserId);
        
                if (tmp)
                {
                    //do nothing the student is already in there
                }
                else
                {                   
                    announcement.User = currentUser;
                    viewedPost.User = currentUser;
                    viewedPost.AnnouncementId = (int)id;
                    db.ViewedPosts.Add(viewedPost);
                    db.SaveChanges();
                }

            }
           
            AnnouncementView AV = populateAnnouncementViewModel((int)id);
            return View(AV);
        }

        // GET: Announcements/Create
        [Authorize(Roles = RoleName.Lecturer)]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Announcements/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = RoleName.Lecturer)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,DateTime,Author,Content")] Announcement announcement)
        {
            if (User.IsInRole(RoleName.Lecturer))
            {
                if (ModelState.IsValid)
                {
                    //get user identity 
                    string currentUserId = User.Identity.GetUserId();
                    ApplicationUser currentUser = db.Users.FirstOrDefault(
                        x => x.Id == currentUserId);
                    announcement.User = currentUser;
                    //Setting the date automatically
                    announcement.DateTime = DateTime.Now;

                    db.Announcements.Add(announcement);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(announcement);
            }
            else
            {
                return RedirectToAction("NotAuthorised");
            }
        }


        // GET: Announcements/Edit/5
        [Authorize(Roles = RoleName.Lecturer)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Announcement announcement = db.Announcements.Find(id);
            if (announcement == null)
            {
                return HttpNotFound();
            }
            if (CanYou((int)id))
            {
                return View(announcement);
            }
            else
            {
                return View("NotAuthorised");
            }
        }

        // POST: Announcements/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = RoleName.Lecturer)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,DateTime,Author,Content")] Announcement announcement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(announcement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(announcement);
        }

        // GET: Announcements/Delete/5
        [Authorize(Roles = RoleName.Lecturer)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Announcement announcement = db.Announcements.Find(id);
            if (announcement == null)
            {
                return HttpNotFound();
            }
            if (CanYou((int)id))
            {
                return View(announcement);
            }
            else
            {
                return View("NotAuthorised");
            }
            
        }

        // POST: Announcements/Delete/5
        [Authorize(Roles = RoleName.Lecturer)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Announcement announcement = db.Announcements.Find(id);
            db.Announcements.Remove(announcement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult BuildAnnouncementTable()
        {
           
            if (User.IsInRole(RoleName.Lecturer))
            {
                return PartialView("_AnnouncementTable", db.Announcements.ToList());
            }
            else
            {
                //return table with limited access for students
                return PartialView("_AnnouncementTableStudent", db.Announcements.ToList());
            }
           
        }

        [Authorize(Roles = RoleName.Lecturer)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AJAXCreate([Bind(Include = "Id,Title,Author,Content")] Announcement announcement)
        {
            if (ModelState.IsValid)
            {
                //get user identity 
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(
                    x => x.Id == currentUserId);
                announcement.User = currentUser;
                //Setting the date automatically
                announcement.DateTime = DateTime.Now;
                announcement.Author = currentUser.Name + " " + currentUser.Surname;

                db.Announcements.Add(announcement);
                db.SaveChanges();

            }

            return PartialView("_AnnouncementTable", db.Announcements.ToList());
        }

        //populate announcements with comments
        public AnnouncementView populateAnnouncementViewModel(int id)
        {
            AnnouncementView AV = new AnnouncementView();
            int currentAnnouncementId = id;
            AV.Announcement = db.Announcements.FirstOrDefault(x => x.Id == id);
            AV.Comments = db.Comments.Where(x => x.AnnouncementId == currentAnnouncementId).ToList();
            return AV;
        }
       
        private IEnumerable<Announcement> GetMyAnnouncements()
        {
            //get user identity 
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(
                x => x.Id == currentUserId);
            return db.Announcements.ToList().Where(x => x.User == currentUser);
        }


        //generate the list of users that have seen the announcement
        [Authorize(Roles = RoleName.Lecturer)]
        public ActionResult SeenList(ViewedPost viewedPost, int id)
        {
            if (ModelState.IsValid)
            {
                return View("SeenList", GetSeen(id));
            }
           
            return View("SeenList", GetSeen(id));
        }

        public bool CanYou(int id)
        {
            if (GetMyAnnouncements().Any(x => x.Id == id))
            {
                return true;
            }
            else
            {
                return false;
            }
            
        }

        private IEnumerable<ViewedPost> GetSeen(int id)
        {

            IEnumerable<ViewedPost> seenPosts = db.ViewedPosts.Where(x => x.AnnouncementId == id).ToList();
            IEnumerable<ApplicationUser> students = db.Users.ToList(); //Where(x=> x.Roles.Equals(RoleName.Lecturer)).ToList();
            int counter = 0;
            foreach (ApplicationUser student in students)
            {
                if(seenPosts.Any(x => x.User.Id == student.Id))
                {
                    counter++;
                }
            }

            ViewBag.Percent = Math.Round(100f * ((float)counter / (float)students.Count()));

            return seenPosts;
        }

    }
}

Web/Controllers/CommentsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        public ActionResult Index()
        {
            return View(GetMyComments());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CommentId,Author,Content")] Comment comment, int? id)
        {
            if(id == null)
            {
                return RedirectToAction("Index", "Announcements");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    string currentUserId = User.Identity.GetUserId();
                    ApplicationUser currentUser = db.Users.FirstOrDefault(
                        x => x.Id == currentUserId);

                    comment.User = currentUser;
                    comment.DateTime = DateTime.Now;
                    comment.Author = currentUser.Name + " " + currentUser.Surname;
                    comment.AnnouncementId = (int)id;

                    db.Comments.Add(comment);
                    db.SaveChanges();
                    return RedirectToAction("Details/" + (id.ToString()), "Announcements");
                }
            }


            return View(comment);
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(
                x => x.Id == currentUserId);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }

            if (comment.User == currentUser)
            {
                return View(comment);
            }
            else
            {
                return View("NotAuthorised");
            }
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CommentId,DateTime,Author,Content,AnnouncementId")] Comment comment)
        {
            

            if (ModelState.IsValid)
            {

                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
                
            }

                return View(comment);

        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(
                x => x.Id == currentUserId);

            Comment comment = db.Comments.Find(id);
            
            if (comment.User == currentUser)
            {
                db.Comments.Remove(comment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View("NotAuthorised");
            }
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private IEnumerable<Comment> GetMyComments()
        {
            //get user identity 
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(
                x => x.Id == currentUserId);
            return db.Comments.ToList().Where(x => x.User == currentUser);
        }
        //Ajax used to create comments
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AjaxCreate([Bind(Include = "CommentId,Author,Content")] Comment comment, int id)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(
                    x => x.Id == currentUserId);

                comment.User = currentUser;
                comment.DateTime = DateTime.Now;
                comment.Author = currentUser.Name + " " + currentUser.Surname;
                comment.AnnouncementId = id;

                db.Comments.Add(comment);
                db.SaveChanges();
                //return RedirectToAction("Details/" + (id.ToString()), "Announcements");
                //return RedirectToAction("_CommentTable", db.Comments.Where(x => x.AnnouncementId == id).ToList());
            }

            //return View(comment);
            return PartialView("_CommentTable", db.Comments.Where(x => x.AnnouncementId == id).ToList());
        }

        public ActionResult BuildCommentTable()
        {
            /*
            //get user identity 
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(
                x => x.Id == currentUserId);
               
            */
            return PartialView("_CommentTable", db.Comments.ToList());

        }
    }
}

Web/Views/Announcements/Create.cshtml
@model Web.Models.Announcement

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Announcement</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Announcements/Delete.cshtml
@model Web.Models.Announcement

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Announcement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web/Views/Announcements/Details.cshtml
@model Web.Models.AnnouncementView

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Announcement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Announcement.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Announcement.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Announcement.DateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Announcement.DateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Announcement.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Announcement.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Announcement.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Announcement.Content)
        </dd>

    </dl>
</div>

<div id="commentsDiv">

    @foreach (var item in Model.Comments)
    {
        <dl>
            <dd>
                @Html.DisplayFor(modelItem => item.Author)
            </dd>
            <dd>
                @Html.DisplayFor(modelItem => item.DateTime)
            </dd>
            <dd>
                @Html.DisplayFor(modelItem => item.Content)
            </dd>
            <dd>
                @Html.ActionLink("Details", "Details","Comments", new { id = item.CommentId },null) 
            </dd>
        </dl>
    }

</div>
    <div id="commentCreateForm">
        @using (Ajax.BeginForm("AJAXCreate", "Comments", new { id = Model.Announcement.Id }, new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "POST",
            UpdateTargetId = "commentsDiv"
        }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Comments</h4>
                <hr />
                <div class="form-group">
                    @Html.LabelFor(model => model.Comment.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Comment.Content, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Comment.Content, "You need to write something", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>

        }
    </div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Announcement.Id }) |
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Comment this Announcement", "Create", "Comments", new { id = Model.Announcement.Id }, null) |
    @Html.ActionLink("Seen by", "SeenList", "Announcements", new { id = Model.Announcement.Id }, null)
</p>

@section Scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/CustomScripts/BuildCommentTable.js"></script>
    @Scripts.Render("~/bundles/jqeuryval")
}

Web/Views/Announcements/Edit.cshtml
@model Web.Models.Announcement

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Announcement</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Announcements/Index.cshtml
@model Web.Models.Announcement

@{
    ViewBag.Title = "Index";
}

<div id="tableDiv"></div>
<div id="announcementCreateForm">
    @using (Ajax.BeginForm("AJAXCreate", "Announcements", new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        UpdateTargetId = "tableDiv"
    }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Announcement</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "A title is necessary", new { @class = "text-danger" })
                </div>
            </div>

            @*
                <div class="form-group">
                    @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
                    </div>
                </div>
            *@
            <div class="form-group">
                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Content, "So is content", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>

    }
</div>

@section Scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/CustomScripts/BuildAnnouncementTable.js"></script>
    @Scripts.Render("~/bundles/jqeuryval")
}

Web/Views/Announcements/IndexStudent.cshtml
@model Web.Models.Announcement

@{
    ViewBag.Title = "Index";
}

<div id="tableDiv"></div>

@section Scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/CustomScripts/BuildAnnouncementTable.js"></script>
    @Scripts.Render("~/bundles/jqeuryval")
}

Web/Views/Announcements/SeenList.cshtml
@model IEnumerable<Web.Models.ViewedPost>
@{
    ViewBag.Title = "SeenList";
}

<h2>SeenList</h2>

<div id="seenBar">
    <p>@(ViewBag.Percent)%</p>
    <div class="progress">
        <div class="progress-bar" role="progressbar" 
             style="width:@(Html.AttributeEncode(ViewBag.Percent))%">

        </div>
    </div>
</div>


@foreach (var item in Model)
{
    <dl>
        <dd>
            @Html.DisplayFor(modelItem => item.User.UserName)
        </dd>
        <dd>
            @Html.DisplayFor(modelItem => item.User.Name)
        </dd>

    </dl>
}

Web/Views/Announcements/_AnnouncementTable.cshtml
@model IEnumerable<Web.Models.Announcement>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>